### ISSUE TITLE
cv les7ab

### ISSUE THREAD

**Issue by aziz0x00** [sons-of-titus/conf.nvim#1]
mere7be bik v theprimeagen club hhh, 3ajib 4ou nharat ane wa7el ella v neovim
-- kent neb9i tov nezreglak msg 9er 4ehou mani vat7 clubhouse v telefouni

**Comment by sons-of-titus** [comment]
hhh wa5yert Aziz,, wallahi tha9el 3liye intellij w vs-code 3gebt gesst nvim, I'm doing Rust these days, and the compiler is heavy on my poor laptop, so I had to get minimal.
My twitter is: @compiler_a drop me a message


![pic-full-230507-1440-32](https://user-images.githubusercontent.com/43900700/236684285-355d0ea4-0e5a-4b9b-87c0-64a8a4044cd9.png)

**Comment by aziz0x00** [comment]
that screenshot is dope bro, Rust 7a9i9iye ba3d, will drop u a msg on twitter nchalah
